### ISSUE TITLE
UnboundLocalError when running ezgmail.unread()

### ISSUE THREAD

**Issue by Larsons1234** [asweigart/ezgmail#27]
Got this error the first time trying out this lib. I have figured out a temporary solution for this by removing the if statement on line 255 in the `__init__.py` file but not sure if it breaks the code elsewhere, it is attached below the error. I also apologise for the bad indentation, I do not know how to properly use GitHub for reporting issues.

Code:
`import ezgmail`
` `
`ezgmail.init()`
`unreadThreads = ezgmail.unread()`
`ezgmail.summary(unreadThreads)`

Error:
`Traceback (most recent call last):
  File "E:\Python\Gmail ecrater orders\ecrater.py", line 5, in <module>
    ezgmail.summary(unreadThreads)
  File "C:\Users\Lauris\AppData\Local\Programs\Python\Python38\lib\site-packages\ezgmail\__init__.py", line 641, in summary
    (obj.senders(), obj.snippet, obj.latestTimestamp())
  File "C:\Users\Lauris\AppData\Local\Programs\Python\Python38\lib\site-packages\ezgmail\__init__.py", line 112, in senders
    for msg in self.messages:
  File "C:\Users\Lauris\AppData\Local\Programs\Python\Python38\lib\site-packages\ezgmail\__init__.py", line 99, in messages
    self._messages.append(GmailMessage(msg))
  File "C:\Users\Lauris\AppData\Local\Programs\Python\Python38\lib\site-packages\ezgmail\__init__.py", line 258, in __init__
    self.originalBody = base64.urlsafe_b64decode(messageObj["payload"]["body"]["data"]).decode(emailEncoding)
UnboundLocalError: local variable 'emailEncoding' referenced before assignment`

Solution from line 253 to 258 in `__init__.py`:
`elif "body" in messageObj["payload"].keys():`
`            for header in messageObj['payload']['headers']:`
`                #if header['name'].upper() == 'CONTENT-TYPE':`
`                emailEncoding = _parseContentTypeHeaderForEncoding(header['value'])`
`            self.originalBody = base64.urlsafe_b64decode(messageObj["payload"]["body"]["data"]).decode(emailEncoding)`
`            self.body = removeQuotedParts(self.originalBody)`

**Comment by RhinoCodes** [comment]
Commenting for visibility

@asweigart Are you aware of this?

**Comment by fridde** [comment]
I am getting this error for some mails, too.
This seems like a bug: In [this line](https://github.com/asweigart/ezgmail/blob/d0241b7d3814686071cd59673f377e7945088af1/src/ezgmail/__init__.py#L283) ```emailEncoding``` is not guaranteed to exist, since it's only created under specific circumstances.

Should we set a default value, @asweigart ? I could create a pull request.
