### ISSUE TITLE
problem with summary

### ISSUE THREAD

**Issue by spoonpaw** [asweigart/ezgmail#8]
got an error when trying to get a summary of threads:

>>> unreadThreads = ezgmail.unread()
>>> ezgmail.summary(unreadThreads)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alex\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ezgmail\__init__.py", line 507, in summary
    summaryText.append((obj.senders(), obj.snippet, obj.latestTimestamp())) # GmailThread and GmailMessage both have senders() and latestTimestamp() methods.
  File "C:\Users\alex\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ezgmail\__init__.py", line 95, in senders
    for msg in self.messages:
  File "C:\Users\alex\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ezgmail\__init__.py", line 83, in messages
    self._messages.append(GmailMessage(msg))
  File "C:\Users\alex\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ezgmail\__init__.py", line 177, in __init__
    self.originalBody = base64.urlsafe_b64decode(part['body']['data']).decode(emailEncoding)
LookupError: unknown encoding: UTF-9

**Comment by asweigart** [comment]
I checked the code, and it seems like whatever email you were trying to retrieve was set to utf-9 (which is a nonexistant encoding), and 'utf-9' doesn't appear anywhere in the ezgmail code. I'm going to close this issue.
